# Generated by Django 4.2.2 on 2023-07-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230702_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.CharField(max_length=11),
        ),
    ]
