# Generated by Django 4.2.2 on 2023-07-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
