# Generated by Django 3.2.7 on 2023-07-02 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.CharField(default=20, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(default=66, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
