# Generated by Django 4.2.2 on 2023-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
