# Generated by Django 4.2.2 on 2023-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_address_alter_user_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='customer_id',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='gst_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
